/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReporteRouteImport } from './routes/reporte'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as ModulosRouteImport } from './routes/modulos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulosIndexRouteImport } from './routes/modulos.index'
import { Route as ModulosIdRouteImport } from './routes/modulos.$id'

const ReporteRoute = ReporteRouteImport.update({
  id: '/reporte',
  path: '/reporte',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosRoute = ModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosIndexRoute = ModulosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModulosRoute,
} as any)
const ModulosIdRoute = ModulosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ModulosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modulos': typeof ModulosRouteWithChildren
  '/registro': typeof RegistroRoute
  '/reporte': typeof ReporteRoute
  '/modulos/$id': typeof ModulosIdRoute
  '/modulos/': typeof ModulosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/registro': typeof RegistroRoute
  '/reporte': typeof ReporteRoute
  '/modulos/$id': typeof ModulosIdRoute
  '/modulos': typeof ModulosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modulos': typeof ModulosRouteWithChildren
  '/registro': typeof RegistroRoute
  '/reporte': typeof ReporteRoute
  '/modulos/$id': typeof ModulosIdRoute
  '/modulos/': typeof ModulosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/modulos'
    | '/registro'
    | '/reporte'
    | '/modulos/$id'
    | '/modulos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/registro' | '/reporte' | '/modulos/$id' | '/modulos'
  id:
    | '__root__'
    | '/'
    | '/modulos'
    | '/registro'
    | '/reporte'
    | '/modulos/$id'
    | '/modulos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModulosRoute: typeof ModulosRouteWithChildren
  RegistroRoute: typeof RegistroRoute
  ReporteRoute: typeof ReporteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reporte': {
      id: '/reporte'
      path: '/reporte'
      fullPath: '/reporte'
      preLoaderRoute: typeof ReporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos': {
      id: '/modulos'
      path: '/modulos'
      fullPath: '/modulos'
      preLoaderRoute: typeof ModulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos/': {
      id: '/modulos/'
      path: '/'
      fullPath: '/modulos/'
      preLoaderRoute: typeof ModulosIndexRouteImport
      parentRoute: typeof ModulosRoute
    }
    '/modulos/$id': {
      id: '/modulos/$id'
      path: '/$id'
      fullPath: '/modulos/$id'
      preLoaderRoute: typeof ModulosIdRouteImport
      parentRoute: typeof ModulosRoute
    }
  }
}

interface ModulosRouteChildren {
  ModulosIdRoute: typeof ModulosIdRoute
  ModulosIndexRoute: typeof ModulosIndexRoute
}

const ModulosRouteChildren: ModulosRouteChildren = {
  ModulosIdRoute: ModulosIdRoute,
  ModulosIndexRoute: ModulosIndexRoute,
}

const ModulosRouteWithChildren =
  ModulosRoute._addFileChildren(ModulosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModulosRoute: ModulosRouteWithChildren,
  RegistroRoute: RegistroRoute,
  ReporteRoute: ReporteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
